### ISSUE TITLE
ClimatologyOverlayFactory.cpp needs a little patch to be built on wxgtk 3.1.5

### ISSUE THREAD

**Issue by filochard** [rgleason/climatology_pi#35]
Hi Rick
Sorry : I've been absent for a long time from internet (someone who's old and ill needs me to be close ...)

I'm trying to switch the whole OpenCPN stuff from wxgtk3.0 to wxgtk3.15
I got a little problem to build the climatology_pi
There's a missing include line in : 
https://github.com/rgleason/climatology_pi/blob/master/src/ClimatologyOverlayFactory.cpp

I created a patch to build it it on a Linux system (as we can't attach a file ending with .patch  I added a .txt to its name !) 
[climatology_pi-1.4.46-add-missing-gl-include.patch.txt](https://github.com/rgleason/climatology_pi/files/9002214/climatology_pi-1.4.46-add-missing-gl-include.patch.txt)

This problem may occur when you will use wxgtk3.1.5 inside flatpak
I hope this will be helpful

**Comment by LeaseOnLife** [comment]
thanks to filochart, that helped me compile on my debian sid with wxgtk 3.2.1

**Comment by rgleason** [comment]
LeaseOnLife, can you test testplugin_pi 1.0.225.1 on the beta catalog and report back?
results and what version OS?
See https://www.cruisersforum.com/forums/f134/opencpn-beta-version-5-7-1-beta-test-1-plugins-271525.html

Also I can add this line to ClimatologyOverlayFactory.cpp if you think it will not mess up other builds.

```
#include "GLES2/gl2.h"
 #endif
 
#include <GL/glx.h>   <---- add this

 #include "climatology_pi.h"
 #include "gldefs.h"
 #include "icons.h"
```

**Comment by LeaseOnLife** [comment]
can't help you there: I am on Debian Sid, for PI and x64 = not a supported platform by the build system.

**Comment by rgleason** [comment]
Well, I've tried this on Climatology as it is not building for Jammy. We will see.

**Comment by rgleason** [comment]
Have to use wx3.0  I am closing this now. It was clarified somewhere else that I can't find. Reopen if necessary.
